data_transfer = read_ltspice_csv(...);

data_transfer.VDS = ...
data_transfer.W = ...
data_transfer.L = ...
data_transfer.Cox = ...

data_output = read_ltspice_step(...);

params = level1_extract(data_transfer,data_output);
